# frozen_string_literal: true

source "https://rubygems.org"

gem 'jwt'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'puma'
gem "pyroscope", "~> 0.5.10"
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sqlite3'

gem 'sorbet-runtime'

group :development do
  gem 'irb'
  gem 'sorbet'
  gem 'tapioca', require: false
  gem "rack-test"
end

gem "pyroscope-otel", "~> 0.1.1"
gem "opentelemetry-sdk", "~> 1.3"
gem "opentelemetry-exporter-otlp", "~> 0.26.1"
gem "opentelemetry-instrumentation-all", "~> 0.52.0"
