# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mysql2-cs-bind` gem.
# Please instead update this file by running `bin/tapioca gem mysql2-cs-bind`.

module Mysql2; end

# source://mysql2-cs-bind//lib/mysql2-cs-bind.rb#5
class Mysql2::Client
  # source://mysql2/0.5.4/lib/mysql2/client.rb#21
  def initialize(opts = T.unsafe(nil)); end

  def abandon_results!; end
  def affected_rows; end
  def async_result; end
  def automatic_close=(_arg0); end
  def automatic_close?; end
  def close; end
  def closed?; end
  def encoding; end
  def escape(_arg0); end

  # source://mysql2/0.5.4/lib/mysql2/client.rb#126
  def find_default_ca_path; end

  # source://mysql2/0.5.4/lib/mysql2/client.rb#160
  def info; end

  def last_id; end
  def more_results?; end
  def next_result; end

  # source://mysql2/0.5.4/lib/mysql2/client.rb#137
  def parse_connect_attrs(conn_attrs); end

  # source://mysql2/0.5.4/lib/mysql2/client.rb#109
  def parse_flags_array(flags, initial = T.unsafe(nil)); end

  # source://mysql2/0.5.4/lib/mysql2/client.rb#98
  def parse_ssl_mode(mode); end

  def ping; end
  def prepare(_arg0); end

  # source://mysql2/0.5.4/lib/mysql2/client.rb#146
  def query(sql, options = T.unsafe(nil)); end

  # source://mysql2/0.5.4/lib/mysql2/client.rb#152
  def query_info; end

  def query_info_string; end

  # source://mysql2/0.5.4/lib/mysql2/client.rb#3
  def query_options; end

  # source://mysql2/0.5.4/lib/mysql2/client.rb#3
  def read_timeout; end

  def reconnect=(_arg0); end
  def select_db(_arg0); end
  def server_info; end
  def session_track(_arg0); end
  def set_server_option(_arg0); end
  def socket; end
  def ssl_cipher; end
  def store_result; end
  def thread_id; end
  def warning_count; end

  # source://mysql2-cs-bind//lib/mysql2-cs-bind.rb#7
  def xquery(sql, *args, **options); end

  private

  def _query(_arg0, _arg1); end
  def charset_name=(_arg0); end
  def connect(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7); end
  def connect_timeout=(_arg0); end
  def default_auth=(_arg0); end
  def default_file=(_arg0); end
  def default_group=(_arg0); end
  def enable_cleartext_plugin=(_arg0); end
  def init_command=(_arg0); end
  def initialize_ext; end
  def local_infile=(_arg0); end
  def read_timeout=(_arg0); end
  def secure_auth=(_arg0); end
  def ssl_mode=(_arg0); end
  def ssl_set(_arg0, _arg1, _arg2, _arg3, _arg4); end
  def write_timeout=(_arg0); end

  class << self
    # source://mysql2/0.5.4/lib/mysql2/client.rb#5
    def default_query_options; end

    def escape(_arg0); end
    def info; end

    # source://mysql2-cs-bind//lib/mysql2-cs-bind.rb#15
    def pseudo_bind(sql, values); end

    # source://mysql2-cs-bind//lib/mysql2-cs-bind.rb#43
    def quote(rawvalue); end

    private

    # source://mysql2/0.5.4/lib/mysql2/client.rb#167
    def local_offset; end
  end
end
