# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `pyroscope-otel` gem.
# Please instead update this file by running `bin/tapioca gem pyroscope-otel`.

# source://pyroscope-otel//lib/pyroscope/otel.rb#7
module Pyroscope
  class << self
    # source://pyroscope/0.5.10/lib/pyroscope.rb#161
    def _add_tags(thread_id, tags); end

    # source://pyroscope/0.5.10/lib/pyroscope.rb#167
    def _remove_tags(thread_id, tags); end

    # source://pyroscope/0.5.10/lib/pyroscope.rb#84
    def configure; end

    # source://pyroscope/0.5.10/lib/pyroscope.rb#80
    def current_config; end

    # source://pyroscope/0.5.10/lib/pyroscope.rb#128
    def initialize_rails_hooks; end

    # source://pyroscope/0.5.10/lib/pyroscope.rb#153
    def remove_tags(*tags); end

    # source://pyroscope/0.5.10/lib/pyroscope.rb#177
    def shutdown; end

    # source://pyroscope/0.5.10/lib/pyroscope.rb#173
    def stop; end

    # source://pyroscope/0.5.10/lib/pyroscope.rb#149
    def tag(tags); end

    # source://pyroscope/0.5.10/lib/pyroscope.rb#139
    def tag_wrapper(tags); end

    # source://pyroscope/0.5.10/lib/pyroscope.rb#157
    def thread_id; end

    private

    # source://pyroscope/0.5.10/lib/pyroscope.rb#187
    def http_headers_to_json(http_headers); end

    # source://pyroscope/0.5.10/lib/pyroscope.rb#183
    def tags_to_string(tags); end
  end
end

# source://pyroscope-otel//lib/pyroscope/otel.rb#8
module Pyroscope::Otel; end

# source://pyroscope-otel//lib/pyroscope/otel.rb#9
class Pyroscope::Otel::Error < ::StandardError; end

# SpanProcessor annotates otel spans with profile_id, profile urls,
# baseline urls
#
# source://pyroscope-otel//lib/pyroscope/otel.rb#13
class Pyroscope::Otel::SpanProcessor
  # @param app_name [String] - pyroscope app name, including ".cpu" suffix.
  # @param pyroscope_endpoint [String] - http address of pyroscope server for span links.
  # @return [SpanProcessor] a new instance of SpanProcessor
  #
  # source://pyroscope-otel//lib/pyroscope/otel.rb#29
  def initialize(app_name, pyroscope_endpoint); end

  # boolean flag option to annotate pyroscope profiles with span name
  #
  # source://pyroscope-otel//lib/pyroscope/otel.rb#23
  def add_span_name; end

  # boolean flag option to annotate pyroscope profiles with span name
  #
  # source://pyroscope-otel//lib/pyroscope/otel.rb#23
  def add_span_name=(_arg0); end

  # boolean flag option to add profiler url to span attributes
  #
  # source://pyroscope-otel//lib/pyroscope/otel.rb#25
  def add_url; end

  # boolean flag option to add profiler url to span attributes
  #
  # source://pyroscope-otel//lib/pyroscope/otel.rb#25
  def add_url=(_arg0); end

  # pyroscope app name, including ".cpu" suffix.
  #
  # source://pyroscope-otel//lib/pyroscope/otel.rb#16
  def app_name; end

  # pyroscope app name, including ".cpu" suffix.
  #
  # source://pyroscope-otel//lib/pyroscope/otel.rb#16
  def app_name=(_arg0); end

  # source://pyroscope-otel//lib/pyroscope/otel.rb#62
  def force_flush(_timeout: T.unsafe(nil)); end

  # source://pyroscope-otel//lib/pyroscope/otel.rb#53
  def on_finish(span); end

  # source://pyroscope-otel//lib/pyroscope/otel.rb#38
  def on_start(span, parent_context); end

  # http address of pyroscope server for span links
  #
  # source://pyroscope-otel//lib/pyroscope/otel.rb#18
  def pyroscope_endpoint; end

  # http address of pyroscope server for span links
  #
  # source://pyroscope-otel//lib/pyroscope/otel.rb#18
  def pyroscope_endpoint=(_arg0); end

  # boolean flag option to annotate spans with profile attributes only on root spans.
  #
  # source://pyroscope-otel//lib/pyroscope/otel.rb#21
  def root_span_only; end

  # boolean flag option to annotate spans with profile attributes only on root spans.
  #
  # source://pyroscope-otel//lib/pyroscope/otel.rb#21
  def root_span_only=(_arg0); end

  # source://pyroscope-otel//lib/pyroscope/otel.rb#64
  def shutdown(_timeout: T.unsafe(nil)); end

  private

  # source://pyroscope-otel//lib/pyroscope/otel.rb#79
  def annotate_span(profile_id, span); end

  # source://pyroscope-otel//lib/pyroscope/otel.rb#84
  def profile_id(span); end

  # source://pyroscope-otel//lib/pyroscope/otel.rb#88
  def profile_url(profile_id); end

  # source://pyroscope-otel//lib/pyroscope/otel.rb#100
  def query(profile_id); end

  # @return [Boolean]
  #
  # source://pyroscope-otel//lib/pyroscope/otel.rb#68
  def root_span?(parent, parent_context); end
end

# source://pyroscope-otel//lib/pyroscope/otel.rb#14
Pyroscope::Otel::SpanProcessor::ZERO_SPAN_ID = T.let(T.unsafe(nil), String)
